# Generated by Django 2.1.3 on 2018-12-04 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportistas', '0001_initial'),
        ('vehiculos', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionEnvio', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('pedido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.PedidoCliente')),
                ('transportista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='transportistas.Transportista')),
                ('vehiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo')),
            ],
        ),
    ]
