# Generated by Django 2.1.3 on 2018-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('tipo', models.CharField(max_length=20)),
                ('fechaMatriculacion', models.DateField()),
                ('kms', models.IntegerField()),
            ],
        ),
    ]
