# Generated by Django 2.1.3 on 2018-12-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9)),
                ('sueldo', models.FloatField()),
                ('planta', models.CharField(max_length=15)),
            ],
        ),
    ]
