# Generated by Django 2.1.3 on 2018-12-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('estado', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('pagada', models.BooleanField()),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('envio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='envios.EnvioCliente')),
            ],
        ),
    ]
